const test=require("node:test"),assert=require("node:assert/strict"),Handouts=require("../content/east-tennessee-handouts.js"),Core=require("../app/core.js");
const gm={role:"gm",campaignId:Handouts.CAMPAIGN_ID},recipient=(actorId="actor-a")=>Core.normalizeRecipientContext({role:"player",campaignId:Handouts.CAMPAIGN_ID,playerKey:`key-${actorId}`,actorId,partyMember:true});
const base=()=>Handouts.normalizeState({namespace:Handouts.CAMPAIGN_ID,actors:{"actor-a":{actorId:"actor-a",ownerKey:"key-actor-a"},"actor-b":{actorId:"actor-b",ownerKey:"key-actor-b"}},handouts:{},timers:{},logs:[]});

test("final collection has stable IDs and no removed or copied-intelligence document",()=>{const s=base(),ids=Object.keys(s.handouts).sort();assert.equal(ids.length,8);assert.deepEqual(ids,Object.keys(Handouts.DEFINITIONS).sort());for(const id of [...Handouts.REMOVED_IDS,Handouts.LEGACY_PACKET_ID])assert.equal(s.handouts[id],undefined);assert.equal(ids.some(id=>/seal|wax|copied-operational/.test(id)),false);});
test("approved telegram is abbreviated traffic and the interpretation is a clue",()=>{const s=base();assert.equal(s.handouts["east-tennessee:administrative-telegram"].body.startsWith("14 BB 7\n\nMSR EBD KXV\nGRNVL TMRW\nACK RCT"),true);assert.match(s.handouts["east-tennessee:monroe-pike-interpretation"].body,/MSR — messenger/);assert.doesNotMatch(s.handouts["east-tennessee:monroe-pike-interpretation"].body,/cipher puzzle/i);});
test("legacy packet reveal migrates to all three dispatches and obsolete placeholders retire",()=>{const s=Handouts.normalizeState({namespace:Handouts.CAMPAIGN_ID,handouts:{"finchs-nest:official-packets":{visibility:"selected",revealed:true,recipientIds:["actor-a"]},"finchs-nest:copied-operational-information":{visibility:"party",revealed:true},"finchs-nest:seal-evidence":{visibility:"party",revealed:true}}});for(const id of Object.keys(s.handouts).filter(id=>id.startsWith("finchs-nest:dispatch-")))assert.deepEqual(s.handouts[id].recipientIds,["actor-a"]);assert.equal(s.handouts[Handouts.LEGACY_PACKET_ID],undefined);for(const id of Handouts.REMOVED_IDS)assert.equal(s.handouts[id],undefined);});
test("normalization refreshes text but preserves durable access state",()=>{let s=base();s.handouts["finchs-nest:dispatch-case"].visibility="party";s.handouts["finchs-nest:dispatch-case"].revealed=true;s.handouts["finchs-nest:dispatch-case"].body="old placeholder";s=Handouts.normalizeState(JSON.parse(JSON.stringify(s)));assert.equal(s.handouts["finchs-nest:dispatch-case"].visibility,"party");assert.equal(s.handouts["finchs-nest:dispatch-case"].revealed,true);assert.match(s.handouts["finchs-nest:dispatch-case"].body,/worn brown leather/);});
test("GM controls recipient access and clients cannot supply adjudication",()=>{const s=base();assert.equal(Handouts.performAction(s,recipient(),{type:"gmHandoutSetAccess",id:"finchs-nest:dispatch-case",visibility:"public"}).ok,false);assert.equal(Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id:"finchs-nest:dispatch-case",visibility:"selected",recipientIds:["actor-b"]}).ok,true);assert.equal(Core.projectCampaignStateForRecipient(s,recipient("actor-a")).handouts["finchs-nest:dispatch-case"],undefined);assert.match(Core.projectCampaignStateForRecipient(s,recipient("actor-b")).handouts["finchs-nest:dispatch-case"].body,/dispatch case/);});
test("unrevealed party documents stay private and reveal projects transcripts without access controls",()=>{const s=base(),id="finchs-nest:personal-letters";Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id,visibility:"party",revealed:false});assert.equal(Core.projectCampaignStateForRecipient(s,recipient()).handouts[id],undefined);Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id,visibility:"party",revealed:true});const h=Core.projectCampaignStateForRecipient(s,recipient()).handouts[id];assert.match(h.transcript,/Your affectionate son,\nLevi/);assert.equal("visibility" in h,false);assert.equal("recipientIds" in h,false);});
test("GM-initialized copied notes remain editable owner-only actor notes",()=>{const s=base();assert.equal(Handouts.performAction(s,gm,{type:"gmHandoutSetActorNotes",actorId:"actor-a",notes:"Rail priority and Lick Creek reinforcement."}).ok,true);assert.equal(Core.projectCampaignStateForRecipient(s,recipient("actor-a")).actors["actor-a"].privateNotes.data.handoutNotes,"Rail priority and Lick Creek reinforcement.");assert.equal(JSON.stringify(Core.projectCampaignStateForRecipient(s,recipient("actor-b"))).includes("Rail priority"),false);});
test("personal letters use approved names and rules reference is player-readable by default",()=>{const s=base(),letters=s.handouts["finchs-nest:personal-letters"].body;for(const name of ["Levi","Martin","Reuben","Andrew Tuttle"])assert.match(letters,new RegExp(`\\b${name}\\b`));for(const old of ["Samuel","Thomas","Eli","Andrew Cole"])assert.doesNotMatch(letters,new RegExp(`\\b${old}\\b`));assert.ok(Core.projectCampaignStateForRecipient(s,recipient()).handouts["east-tennessee:player-rules-reference"]);});
test("canonical presentation names do not alter handout or scene machine IDs",()=>{const ids=Object.keys(Handouts.DEFINITIONS);assert.ok(ids.includes("finchs-nest:dispatch-case"));assert.equal(Handouts.DEFINITIONS["east-tennessee:monroe-pike-interpretation"].title,"Monroe Pike’s Annotated Interpretation");assert.equal(ids.some(id=>/monroe-pike/.test(id)&&id!=="east-tennessee:monroe-pike-interpretation"),false);});
