const test=require("node:test"),assert=require("node:assert/strict");
const Health=require("../content/east-tennessee-health.js"),Rounds=require("../content/east-tennessee-rounds.js"),Combat=require("../content/east-tennessee-combat.js"),Equipment=require("../content/east-tennessee-equipment.js"),NPCs=require("../content/east-tennessee-npcs.js");
const {projectCampaignStateForRecipient,normalizeRecipientContext}=require("../app/core.js"),gm={role:"gm",campaignId:NPCs.CAMPAIGN_ID},player=(key,actorId="pc")=>normalizeRecipientContext({role:"player",campaignId:NPCs.CAMPAIGN_ID,playerKey:key,actorId,partyMember:true});
function base(){return Equipment.normalizeState(Rounds.normalizeState(Health.normalizeState({namespace:NPCs.CAMPAIGN_ID,actors:{},npcs:{},logs:[],scene:{id:"test",immediateDanger:false},structuredPlay:{},weapons:{},cylinders:{}})));}
function add(s,id,label){const r=NPCs.performAction(s,gm,{type:"gmNpcInstantiate",definitionId:id,visibleLabel:label});assert.equal(r.ok,true);return r.npcId;}

test("required named roster and generic templates have stable immutable definitions",()=>{for(const id of ["parsons-caldwell","will-mercer","hiram-vance","caleb-rader","mose-gentry","abner-raines","isaac-bell","daniel","confederate-guard","confederate-marksman","mounted-messenger","work-camp-laborer","craftsman","hired-out-enslaved-laborer","civilian-bystander"])assert.equal(NPCs.DEFINITIONS[id].id,id);assert.ok(Object.isFrozen(NPCs.DEFINITIONS));assert.equal("gmSummary" in NPCs.PUBLIC_DEFINITIONS["will-mercer"],false);assert.equal("faction" in NPCs.PUBLIC_DEFINITIONS["daniel"],false);});
test("skill resolution distinguishes explicit, fallback, and unavailable checks",()=>{assert.deepEqual(NPCs.resolveSkill("hiram-vance","awareness"),{source:"explicit",value:12});assert.deepEqual(NPCs.resolveSkill("hiram-vance","athletics"),{source:"campaignFallback",value:8});assert.deepEqual(NPCs.resolveSkill("will-mercer","firearms"),{source:"unavailable",value:null});});
test("templates create unique live IDs and normalization never duplicates roster state",()=>{const s=base(),a=add(s,"confederate-guard"),b=add(s,"confederate-guard");assert.notEqual(a,b);assert.equal(Object.keys(s.npcs).length,2);const twice=NPCs.normalizeState(NPCs.normalizeState(s));assert.equal(Object.keys(twice.npcs).length,2);assert.equal(twice.actors[a].actorId,a);});
test("named NPCs use full health while minor extras go Down stable without Dying",()=>{const s=base(),v=add(s,"hiram-vance"),g=add(s,"confederate-guard");assert.equal(s.actors[v].healthClassification,"full");assert.equal(s.actors[g].healthClassification,"minorExtra");Health.performAction(s,gm,{type:"applySeriousHit",targetActorId:g,description:"serious hit"});assert.equal(s.actors[g].health.state,"wounded");s.actors[g].health.state="unhurt";Combat.performAction(s,gm,{type:"requestAttack",attackerActorId:v,targetActorId:g,weaponId:"rifle-musket",bypassReaction:true},{rollD20:()=>1});Combat.performAction(s,gm,{type:"gmConfirmHitConsequence",attackId:s.attacks[0].id});assert.equal(s.actors[g].health.state,"down");assert.equal(s.actors[g].health.stable,true);assert.equal(s.actors[g].health.dyingFailures,0);});
test("only the GM changes morale, status, identity, class, and delegation",()=>{const s=base(),id=add(s,"will-mercer");for(const action of [{type:"gmNpcSetState",moraleState:"fleeing"},{type:"gmNpcSetIdentity",revealed:true},{type:"gmNpcDelegate",playerKey:"p1"}])assert.equal(NPCs.performAction(s,{role:"player",playerKey:"p1"},{...action,npcId:id}).ok,false);assert.equal(NPCs.performAction(s,gm,{type:"gmNpcSetState",npcId:id,moraleState:"fleeing",revealMorale:true,sceneStatus:"fled"}).ok,true);assert.equal(NPCs.isAvailable(s.npcs[id],s.actors[id]),false);assert.equal(NPCs.performAction(s,gm,{type:"gmNpcRestore",npcId:id}).ok,true);assert.equal(NPCs.isAvailable(s.npcs[id],s.actors[id]),true);});
test("injury and ally defeat never automate morale",()=>{const s=base(),a=add(s,"caleb-rader"),b=add(s,"mose-gentry");Health.performAction(s,gm,{type:"applyCriticalHit",targetActorId:a,description:"hit"});Health.performAction(s,gm,{type:"applyCriticalHit",targetActorId:b,description:"hit"});assert.equal(s.npcs[a].moraleState,"steady");assert.equal(s.npcs[b].moraleState,"steady");});
test("identity projection omits canonical secrets and reveals without replacing actor",()=>{const s=base(),id=add(s,"will-mercer"),p=player("other"),hidden=projectCampaignStateForRecipient(s,p);assert.equal(hidden.npcs[id].label,"Young Courier");assert.equal(JSON.stringify(hidden).includes("dispatches and personal letters"),false);assert.equal(JSON.stringify(hidden).includes("Confederate courier"),false);NPCs.performAction(s,gm,{type:"gmNpcSetNotes",npcId:id,gmNotes:"private future-scene note"});NPCs.performAction(s,gm,{type:"gmNpcSetIdentity",npcId:id,revealed:true});assert.equal(s.actors[id].actorId,id);assert.equal(s.npcs[id].id,id);const shown=projectCampaignStateForRecipient(s,p);assert.equal(shown.npcs[id].label,"Will Mercer");assert.equal(JSON.stringify(shown).includes("private future-scene note"),false);assert.equal(projectCampaignStateForRecipient(s,gm).npcs[id].gmNotes,"private future-scene note");});
test("delegation grants mechanics without narrative and revocation removes it immediately",()=>{const s=base(),id=add(s,"hiram-vance");NPCs.performAction(s,gm,{type:"gmNpcSetNotes",npcId:id,gmNotes:"secret tactics"});NPCs.performAction(s,gm,{type:"gmNpcDelegate",npcId:id,playerKey:"p1"});let view=projectCampaignStateForRecipient(s,player("p1"));assert.equal(view.npcs[id].mechanicalControl,true);assert.equal(JSON.stringify(view).includes("secret tactics"),false);assert.equal(Health.performAction(s,{role:"player",playerKey:"p1",actorId:"pc"},{type:"requestSkillCheck",actorId:id,skillId:"awareness"},{rollD20:()=>5}).ok,true);NPCs.performAction(s,gm,{type:"gmNpcDelegate",npcId:id,playerKey:""});view=projectCampaignStateForRecipient(s,player("p1"));assert.equal(view.npcs[id].mechanicalControl,undefined);assert.equal(Health.performAction(s,{role:"player",playerKey:"p1",actorId:"pc"},{type:"requestSkillCheck",actorId:id,skillId:"awareness"},{rollD20:()=>5}).ok,false);});
test("NPC firearms persist canonical loaded and reserve state",()=>{let s=base(),id=add(s,"hiram-vance"),wid=s.actors[id].weaponInstanceIds[0];s=Equipment.normalizeState(s);const w=s.weapons[wid];assert.equal(Equipment.loaded(s,w),1);assert.equal(Equipment.discharge(s,w).ok,true);assert.equal(Equipment.loaded(s,w),0);const saved=Equipment.normalizeState(JSON.parse(JSON.stringify(s)));assert.equal(Equipment.loaded(saved,saved.weapons[wid]),0);assert.equal(Equipment.performAction(saved,gm,{type:"reloadWeapon",actorId:id,weaponInstanceId:wid,gmWaiveAction:true}).ok,true);assert.equal(Equipment.loaded(saved,saved.weapons[wid]),1);});
test("groups share initiative, noncombatants do not auto-enter, and unavailable actors cannot act",()=>{const s=base(),a=add(s,"confederate-guard"),b=add(s,"confederate-guard"),civilian=add(s,"civilian-bystander");Rounds.performAction(s,gm,{type:"startStructuredPlay"});Rounds.performAction(s,gm,{type:"setParticipants",participants:[{id:"a",actorId:a,kind:"extra",active:true,initiativeGroupId:"guards"},{id:"b",actorId:b,kind:"extra",active:true,initiativeGroupId:"guards"}]});Rounds.performAction(s,gm,{type:"rollInitiative"},{rollDie:()=>4});assert.equal(s.structuredPlay.initiativeEntries.length,1);assert.equal(s.structuredPlay.participants.some(p=>p.actorId===civilian),false);NPCs.performAction(s,gm,{type:"gmNpcSetState",npcId:a,sceneStatus:"captured",moraleState:"captured"});assert.equal(s.structuredPlay.participants.find(p=>p.actorId===a).active,false);});
test("badge priority is deterministic and only revealed morale enters player state",()=>{const s=base(),id=add(s,"caleb-rader");NPCs.performAction(s,gm,{type:"gmNpcSetState",npcId:id,sceneStatus:"surrendered",moraleState:"surrendered"});assert.equal(NPCs.tokenBadge(s,id),"SURRENDERED");s.actors[id].health.state="wounded";assert.equal(NPCs.tokenBadge(s,id),"WOUNDED");s.actors[id].health.state="down";s.actors[id].health.stable=false;assert.equal(NPCs.tokenBadge(s,id),"DOWN · UNSTABLE");s.actors[id].health.dead=true;assert.equal(NPCs.tokenBadge(s,id),"DEAD");const view=projectCampaignStateForRecipient(s,player("p"));assert.equal(view.npcs[id].moraleState,undefined);});
