const test=require("node:test"),assert=require("node:assert/strict"),Core=require("../app/core.js");
require("../content/catalog.js");
const Health=require("../content/east-tennessee-health.js"),Rounds=require("../content/east-tennessee-rounds.js"),Characters=require("../content/east-tennessee-characters.js"),Talents=require("../content/east-tennessee-talents.js"),NPCs=require("../content/east-tennessee-npcs.js"),Handouts=require("../content/east-tennessee-handouts.js"),Finchs=require("../content/east-tennessee-finchs-nest.js"),Lick=require("../content/east-tennessee-lick-creek.js");
require("../content/east-tennessee-equipment.js");require("../content/east-tennessee-combat.js");require("../content/campaigns.js");
const campaign=globalThis.VTTCampaigns.get("east-tennessee-1861"),gm={role:"gm",campaignId:campaign.id},clone=v=>JSON.parse(JSON.stringify(v));
const claim=(s,id,key)=>Characters.performAction(s,{role:"player",campaignId:campaign.id,playerKey:key},{type:"claimCharacter",characterId:id,expectedSequence:s.characterClaimSequence});
const guardCount=s=>Object.keys(s.lickCreek.npcIds).filter(k=>k==="vance"||k==="rader"||k==="mose"||k.startsWith("guard-")).length;
function fresh(){return campaign.createSession().campaignState;}
function fourPlayers(s){for(const [i,id] of Object.keys(Characters.DEFINITIONS).slice(0,4).entries())assert.equal(claim(s,id,`player-${i+1}`).ok,true);}
function reload(s){return campaign.normalizeCampaignState(clone(s));}

test("complete quiet-success dry run survives reload and local resets",()=>{let s=fresh();fourPlayers(s);const clara=Characters.DEFINITIONS["clara-webb"].actorId;
 assert.equal(Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id:"east-tennessee:administrative-telegram",visibility:"selected",recipientIds:[clara]}).ok,true);
 assert.equal(Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id:"east-tennessee:monroe-pike-interpretation",visibility:"party",revealed:true}).ok,true);
 assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsInitialize"}).ok,true);assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsInitialize"}).ok,false);
 Finchs.performAction(s,gm,{type:"gmFinchsSetPhase",phaseId:"deep-night"});Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"heldByPlayer",sealCondition:"openedCleanly",contentsAccessed:true,officialPacketsInspected:true,personalLettersHandled:true,returnedToOriginalLocation:true,willAwareOfCompromise:false,gmNotes:"Opened and returned without an automatic seal ruling."}});
 Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id:"finchs-nest:dispatch-rail-priority",visibility:"party",revealed:true});Handouts.performAction(s,gm,{type:"gmHandoutSetAccess",id:"finchs-nest:personal-letters",visibility:"selected",recipientIds:[clara]});
 Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"beneathPillow",returnedToOriginalLocation:true}});Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"cleanInspectionAndReturn"});Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"baseline"});
 assert.equal(Lick.performAction(s,gm,{type:"gmLickInitialize",variant:"undetermined",abnerWeapon:"revolver"}).ok,true);assert.equal(guardCount(s),6);Lick.performAction(s,gm,{type:"gmLickRevealFact",factId:"guard-count",visibility:"selected",actorIds:[clara]});
 assert.equal(Lick.performAction(s,gm,{type:"gmLickStartStageTwo"}).ok,false);assert.equal(Lick.performAction(s,gm,{type:"gmLickStartFire",category:"custom",initialRounds:1}).ok,true);assert.equal(Lick.performAction(s,gm,{type:"gmLickStartFire",category:"competent"}).ok,false);
 Rounds.performAction(s,gm,{type:"startStructuredPlay",sceneId:"lick-creek"});Rounds.performAction(s,gm,{type:"setParticipants",participants:[]});Rounds.performAction(s,gm,{type:"rollInitiative"});Rounds.performAction(s,gm,{type:"startFirstTurn"});Rounds.performAction(s,gm,{type:"endRound"});Lick.normalizeState(s);assert.equal(s.lickCreek.bridgeState,"disabled");assert.ok(s.lickCreek.fireState.stageTwoTimerId);
 Lick.performAction(s,gm,{type:"gmLickSetOutcome",outcome:"bridgeDisabled",notes:"Party escaped after a competent fire."});s=reload(s);assert.equal(s.finchsNest.courierOutcome,"cleanInspectionAndReturn");assert.equal(s.finchsNest.lickCreekVariant,"baseline");assert.equal(s.lickCreek.missionOutcome,"bridgeDisabled");assert.equal(s.lickCreek.bridgeState,"disabled");assert.equal(guardCount(s),6);assert.equal(Object.values(s.actors).filter(a=>a.ownerKey).length,4);
 const before={health:clone(s.actors[clara].health),owners:Object.fromEntries(Object.entries(s.actors).map(([id,a])=>[id,a.ownerKey])),handouts:clone(s.handouts),outcome:s.lickCreek.missionOutcome};Rounds.performAction(s,gm,{type:"stopStructuredPlay",overrideActiveTimers:true});Lick.performAction(s,gm,{type:"gmLickReset",confirm:true});Finchs.performAction(s,gm,{type:"gmFinchsReset",confirm:true});assert.deepEqual(s.actors[clara].health,before.health);assert.deepEqual(Object.fromEntries(Object.entries(s.actors).map(([id,a])=>[id,a.ownerKey])),before.owners);assert.deepEqual(s.handouts,before.handouts);assert.equal(s.lickCreek.missionOutcome,before.outcome);
});

test("complete compromised path sequences alarm, help, reinforcement, evidence, and reload",()=>{let s=fresh();fourPlayers(s);Finchs.performAction(s,gm,{type:"gmFinchsInitialize"});Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"removedFromScene",missingDiscovered:true,willAwareOfCompromise:true}});Finchs.performAction(s,gm,{type:"gmFinchsSetWitnesses",witnessNotes:{facesVisible:"Mattie saw two faces"},evidenceNotes:"A room latch was disturbed."});Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"caseStolen"});Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"alarmed"});Lick.performAction(s,gm,{type:"gmLickInitialize",variant:"undetermined",abnerWeapon:"shotgun"});assert.equal(guardCount(s),8);
 assert.equal(Lick.performAction(s,gm,{type:"gmLickStartTimer",kind:"helpWarned",initialRounds:12}).ok,false);assert.equal(Lick.performAction(s,gm,{type:"gmLickConfirmMessenger",escaped:true,notes:"GM confirms escape southeast."}).ok,true);const snapshot=clone(s);assert.equal(Lick.performAction(s,gm,{type:"gmLickConfirmMessenger",escaped:true}).ok,false);assert.deepEqual(s,snapshot);
 assert.equal(Lick.performAction(s,gm,{type:"gmLickStartTimer",kind:"helpWarned",initialRounds:12}).ok,true);assert.equal(Lick.performAction(s,gm,{type:"gmLickStartTimer",kind:"helpWarned",initialRounds:12}).ok,false);const help=s.timers[s.lickCreek.activeTimers.helpWarned];Rounds.performAction(s,gm,{type:"timerCommand",timerId:help.id,command:"resolve"});const reinforcements=Object.values(s.timers).find(t=>t.definitionId==="reinforcements-arrive");assert.ok(reinforcements);Rounds.performAction(s,gm,{type:"timerCommand",timerId:reinforcements.id,command:"resolve"});Lick.performAction(s,gm,{type:"gmLickSetEvidence",witnessNotes:{visibleFaces:"A guard saw Clara"},evidenceNotes:"Tracks and a dropped tool remain."});s=reload(s);assert.equal(s.adventureFlags.helpWarned,true);assert.equal(s.adventureFlags.reinforcementsArrived,true);assert.equal(s.finchsNest.evidenceNotes,"A room latch was disturbed.");assert.equal(s.lickCreek.evidenceNotes,"Tracks and a dropped tool remain.");assert.equal(guardCount(s),8);
});

test("legitimate withdrawal preserves secrecy and an intact bridge",()=>{let s=fresh();Finchs.performAction(s,gm,{type:"gmFinchsInitialize"});Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"alarmed"});Lick.performAction(s,gm,{type:"gmLickInitialize",variant:"undetermined",abnerWeapon:"revolver"});Lick.performAction(s,gm,{type:"gmLickRevealFact",factId:"guard-count",visibility:"party"});Lick.performAction(s,gm,{type:"gmLickRevealFact",factId:"alert-posture",visibility:"party"});Lick.performAction(s,gm,{type:"gmLickSetOutcome",outcome:"partyWithdrawn",notes:"Withdrew unseen after reconnaissance."});s=reload(s);assert.equal(s.lickCreek.missionOutcome,"partyWithdrawn");assert.equal(s.lickCreek.bridgeState,"intact");assert.equal(s.lickCreek.evidenceNotes,"");assert.equal(s.adventureFlags.helpWarned,false);assert.equal(Object.keys(s.timers).length,0);assert.match(Lick.ENDINGS.withdrawal,/prudent judgment/i);});

test("schemas 8 through 12 migrate idempotently without duplicating NPCs or resetting durable state",()=>{for(const schema of [8,9,10,11,12]){let s=fresh(),elias=Characters.DEFINITIONS["elias-rourke"].actorId;s.actors[elias].health.state="wounded";s.actors[elias].ownerKey="legacy-owner";s.actors[elias].reserveAmmunition.revolver36=9;if(schema>=8)NPCs.performAction(s,gm,{type:"gmNpcInstantiate",definitionId:"will-mercer"});if(schema>=9){Finchs.performAction(s,gm,{type:"gmFinchsInitialize"});Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"caseStolen"});Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"alarmed"});}else delete s.finchsNest;if(schema>=10&&s.finchsNest)Lick.performAction(s,gm,{type:"gmLickInitialize",variant:"undetermined",abnerWeapon:"revolver"});else delete s.lickCreek;if(schema===11)s.handouts["finchs-nest:official-packets"]={id:"finchs-nest:official-packets",visibility:"party",revealed:true};if(schema===12){s.sceneLevels={"finchs-nest:ground":{name:"Edited ground"}};s.sceneLevelStates={"finchs-nest:ground":{revealed:{room:true}}};s.activeSceneLevel="finchs-nest:ground";}else s.handouts={};const once=reload(s),twice=reload(once);assert.deepEqual(twice,once);assert.equal(once.actors[elias].health.state,"wounded");assert.equal(once.actors[elias].ownerKey,"legacy-owner");assert.equal(once.actors[elias].reserveAmmunition.revolver36,9);assert.equal(new Set(Object.keys(once.npcs)).size,Object.keys(once.npcs).length);if(schema!==12)assert.equal(once.handouts["finchs-nest:official-packets"],undefined);if(schema===12){assert.equal(once.sceneLevels["finchs-nest:ground"].name,"Edited ground");assert.equal(once.activeSceneLevel,"finchs-nest:ground");}assert.equal(once.actors[Characters.DEFINITIONS["jacob-sloane"].actorId].identity.name,"Jacob Hatcher");}
});

test("canonical display names are stable while compatibility IDs remain",()=>{assert.equal(Characters.DEFINITIONS["jacob-sloane"].name,"Jacob Hatcher");assert.equal(NPCs.DEFINITIONS["parsons-caldwell"].displayName,"Gideon Caldwell");assert.equal(NPCs.DEFINITIONS["jasper-murdock"].displayName,"Jasper Murdock");assert.equal(NPCs.DEFINITIONS["druggist-telegraph-operator"].displayName,"Monroe Pike");assert.equal(NPCs.DEFINITIONS.daniel.displayName,"Daniel Cole");const facing=JSON.stringify({characters:Object.values(Characters.DEFINITIONS),npcs:Object.values(NPCs.DEFINITIONS),handouts:Object.values(Handouts.DEFINITIONS),finchs:Finchs.DEFINITION,lick:Lick.DEFINITION});for(const retired of ["Parsons Caldwell","Mountain Gazette","Jacob Sloane","Jasper “Old Eye” Murdock","Druggist / Telegraph Operator"])assert.equal(facing.includes(retired),false,retired);for(const approved of ["Gideon Caldwell","Pigeon Valley Sentinel","Jacob Hatcher","Jasper Murdock","Monroe Pike","Daniel Cole","Martha “Mattie” Finch","Captain Silas Wheellock"])assert.equal(facing.includes(approved),true,approved);});

test("Palimpsest remains isolated from East Tennessee state and handouts",()=>{const p=globalThis.VTTCampaigns.get("palimpsest").createSession();assert.deepEqual(p.campaignState,{});assert.equal(JSON.stringify(p).includes("east-tennessee"),false);assert.equal(JSON.stringify(p).includes("finchs-nest"),false);});
