const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const Health=require("../content/east-tennessee-health.js"),Rounds=require("../content/east-tennessee-rounds.js"),Combat=require("../content/east-tennessee-combat.js"),Equipment=require("../content/east-tennessee-equipment.js"),NPCs=require("../content/east-tennessee-npcs.js"),Finchs=require("../content/east-tennessee-finchs-nest.js"),Core=require("../app/core.js");
const gm={role:"gm",campaignId:Finchs.CAMPAIGN_ID},player=()=>Core.normalizeRecipientContext({role:"player",campaignId:Finchs.CAMPAIGN_ID,playerKey:"p1",actorId:"pc",partyMember:true});
function base(){return Finchs.normalizeState(NPCs.normalizeState(Equipment.normalizeState(Rounds.normalizeState(Health.normalizeState({namespace:Finchs.CAMPAIGN_ID,actors:{},npcs:{},logs:[],handouts:{},scene:{id:"placeholder",immediateDanger:false},structuredPlay:{},weapons:{},cylinders:{}})))));}
function init(){const s=base(),r=Finchs.performAction(s,gm,{type:"gmFinchsInitialize"});assert.equal(r.ok,true);return s;}

test("stable definition contains approved floors, regions, overlays, and namespaced unlabeled assets",()=>{assert.equal(Finchs.DEFINITION.id,"finchs-nest");for(const floor of ["exterior","ground","upper"]){const map=Finchs.MAPS[floor];assert.match(map.asset,/^assets\/campaigns\/east-tennessee-1861\/finchs-nest\//);assert.ok(Finchs.REGIONS[floor].length>=4);const svg=fs.readFileSync(path.join(__dirname,"..",map.asset),"utf8");assert.equal(/Will's room|noisy|stable-roof|GM/i.test(svg),false);}assert.ok(Finchs.OVERLAY.some(x=>x.id==="noisy-board"));assert.ok(Finchs.OVERLAY.some(x=>x.id==="roof-access"));});
test("initialization is deliberate, once-only, and creates canonical unique scene NPCs",()=>{const s=base();assert.equal(s.finchsNest.initialized,false);assert.equal(Object.keys(s.npcs).length,0);assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsInitialize"}).ok,true);assert.equal(Object.keys(s.finchsNest.npcIds).length,6);assert.equal(new Set(Object.values(s.finchsNest.npcIds)).size,6);assert.equal(s.npcs[s.finchsNest.npcIds.will].definitionId,"will-mercer");assert.equal(s.actors[s.finchsNest.npcIds.will].skills.riding,10);assert.equal(s.npcs[s.finchsNest.npcIds.innkeeper].npcClass,"noncombatant");assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsInitialize"}).ok,false);});
test("initial case, handout placeholders, and rounds remain dormant",()=>{const s=init();assert.equal(s.finchsNest.caseState.location,"beneathCoat");assert.equal(s.finchsNest.caseState.concealed,true);assert.equal(Object.keys(s.handouts).filter(k=>k.startsWith("finchs-nest:")).length,5);assert.equal(Object.values(s.handouts).every(h=>h.visibility==="gm"&&h.placeholder),true);assert.equal(s.structuredPlay.active,false);});
test("GM may select every phase while players cannot and nothing advances in real time",()=>{const s=init();for(const phase of Finchs.PHASES)assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsSetPhase",phaseId:phase.id}).ok,true);assert.equal(s.finchsNest.phaseId,"departure");assert.equal(Finchs.performAction(s,{role:"player",playerKey:"p1"},{type:"gmFinchsSetPhase",phaseId:"arrival"}).ok,false);const saved=Finchs.normalizeState(JSON.parse(JSON.stringify(s)));assert.equal(saved.finchsNest.phaseId,"departure");assert.equal(saved.structuredPlay.active,false);});
test("phase suggestions respect explicit Will and case locations",()=>{const s=init(),will=s.finchsNest.npcIds.will;Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"heldByPlayer",sealCondition:"openedCleanly"}});Finchs.performAction(s,gm,{type:"gmFinchsSetNpcLocation",npcId:will,floor:"exterior",regionId:"road-approach",x:200,y:150,visible:true});Finchs.performAction(s,gm,{type:"gmFinchsSetPhase",phaseId:"deep-night"});assert.equal(s.finchsNest.caseState.location,"heldByPlayer");assert.equal(s.finchsNest.npcLocations[will].regionId,"road-approach");});
test("case state is GM-only, sequence-free, persistent, and ignores player facts",()=>{const s=init();assert.equal(Finchs.performAction(s,{role:"player",playerKey:"p1"},{type:"gmFinchsSetCase",caseState:{location:"removedFromScene",contentsAccessed:true}}).ok,false);assert.equal(s.finchsNest.caseState.location,"beneathCoat");assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"removedFromScene",sealCondition:"damaged",contentsAccessed:true,personalLettersHandled:true}}).ok,true);const saved=Finchs.normalizeState(JSON.parse(JSON.stringify(s)));assert.equal(saved.finchsNest.caseState.location,"removedFromScene");assert.equal(saved.finchsNest.caseState.sealCondition,"damaged");assert.equal(saved.finchsNest.caseState.personalLettersHandled,true);});
test("player projection omits concealed case, routes, locations, witnesses, and guidance",()=>{const s=init();s.finchsNest.witnessNotes.sawParty="Innkeeper recognized Clara";s.finchsNest.evidenceNotes="Dropped knife";s.finchsNest.gmNotes="Private route note";let projected=Core.projectCampaignStateForRecipient(s,player()),raw=JSON.stringify(projected);assert.equal(raw.includes("beneathCoat"),false);assert.equal(raw.includes("Innkeeper recognized"),false);assert.equal(raw.includes("Dropped knife"),false);assert.equal(raw.includes("roof-access"),false);assert.equal(raw.includes("npcLocations"),false);Finchs.performAction(s,gm,{type:"gmFinchsReveal",domain:"object",id:"dispatch-case",revealed:true});Finchs.performAction(s,gm,{type:"gmFinchsReveal",domain:"region",id:"common-room",revealed:true});projected=Core.projectCampaignStateForRecipient(s,player());assert.equal(projected.finchsNest.objects["dispatch-case"].label,"Leather dispatch case");assert.equal(projected.finchsNest.regions[0].label,"Common room");assert.equal(JSON.stringify(projected).includes("Contains sealed official"),false);assert.equal(Core.projectCampaignStateForRecipient(s,gm).finchsNest.witnessNotes.sawParty,"Innkeeper recognized Clara");});
test("witnesses and evidence are descriptive GM records rather than a score",()=>{const s=init();assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsSetWitnesses",witnessNotes:{facesVisible:"Two faces in lamplight",heardUnusualActivity:"Creak after midnight"},evidenceNotes:"Tracks in yard"}).ok,true);assert.equal(s.finchsNest.witnessNotes.facesVisible,"Two faces in lamplight");assert.equal(s.finchsNest.evidenceNotes,"Tracks in yard");assert.equal("evidenceScore" in s.finchsNest,false);});
test("outcomes suggest but never automatically select Lick Creek variant",()=>{const s=init();Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"cleanInspectionAndReturn"});assert.equal(s.finchsNest.suggestedLickCreekVariant,"baseline");assert.equal(s.finchsNest.lickCreekVariant,"undetermined");Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"alarmed"});assert.equal(s.finchsNest.lickCreekVariant,"alarmed");Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"WillMissing"});assert.equal(s.finchsNest.suggestedLickCreekVariant,"undetermined");assert.equal(s.finchsNest.lickCreekVariant,"alarmed");});
test("courier outcome remains private until intentionally revealed",()=>{const s=init();Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"caseStolen",revealed:false});assert.equal(Core.projectCampaignStateForRecipient(s,player()).finchsNest.courierOutcome,undefined);Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"caseStolen",revealed:true});assert.equal(Core.projectCampaignStateForRecipient(s,player()).finchsNest.courierOutcome,"caseStolen");});
test("reset requires confirmation and preserves committed history and ammunition",()=>{const s=init(),will=s.finchsNest.npcIds.will;s.actors[will].reserveAmmunition.pistol=3;Finchs.performAction(s,gm,{type:"gmFinchsSetWitnesses",witnessNotes:{sawParty:"yes"},evidenceNotes:"blood"});Finchs.performAction(s,gm,{type:"gmFinchsSetOutcome",courierOutcome:"caseStolen"});Finchs.performAction(s,gm,{type:"gmFinchsConfirmVariant",variant:"alarmed"});Finchs.performAction(s,gm,{type:"gmFinchsSetCase",caseState:{location:"removedFromScene"}});assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsReset"}).ok,false);assert.equal(Finchs.performAction(s,gm,{type:"gmFinchsReset",confirm:true}).ok,true);assert.equal(s.finchsNest.caseState.location,"beneathCoat");assert.equal(s.finchsNest.witnessNotes.sawParty,"yes");assert.equal(s.finchsNest.evidenceNotes,"blood");assert.equal(s.finchsNest.courierOutcome,"caseStolen");assert.equal(s.finchsNest.lickCreekVariant,"alarmed");assert.equal(s.actors[will].reserveAmmunition.pistol,3);});
test("normalization creates a dormant package without changing existing schema-8 state",()=>{const old={namespace:Finchs.CAMPAIGN_ID,actors:{pc:{actorId:"pc",ownerKey:"owner",identity:{name:"PC"},health:{state:"wounded"},skills:{resolve:10},reserveAmmunition:{pistol:4}}},npcs:{},timers:{t:{id:"t",definitionId:"custom",label:"timer",state:"paused",initialRounds:5,remainingRounds:3}},talentUsage:{scene:{sharpEyeUsed:true}}};const n=Finchs.normalizeState(old);assert.equal(n.finchsNest.initialized,false);assert.equal(n.actors.pc.health.state,"wounded");assert.equal(n.actors.pc.ownerKey,"owner");assert.equal(n.actors.pc.reserveAmmunition.pistol,4);assert.equal(n.timers.t.remainingRounds,3);assert.equal(n.talentUsage.scene.sharpEyeUsed,true);});
