const test=require("node:test"),assert=require("node:assert/strict");
const Health=require("../content/east-tennessee-health.js"),Rounds=require("../content/east-tennessee-rounds.js"),Combat=require("../content/east-tennessee-combat.js");
const {projectCampaignStateForRecipient,normalizeRecipientContext}=require("../app/core.js");
const A="attacker",B="defender",C="ally",gm={role:"gm"},owner=(id,key)=>({role:"player",campaignId:Health.CAMPAIGN_ID,actorId:id,playerKey:key,partyMember:true});
function fixture(){return Combat.normalizeState(Rounds.normalizeState(Health.normalizeState({namespace:Health.CAMPAIGN_ID,actors:{
 [A]:{ownerKey:"a-key",identity:{name:"Ada"},health:{state:"unhurt"},skills:{firearms:12,melee:11,resolve:10},weaponIds:["revolver","knife"]},
 [B]:{ownerKey:"b-key",identity:{name:"Ben"},health:{state:"unhurt"},skills:{firearms:9,melee:10,resolve:10},weaponIds:["club"]},
 [C]:{ownerKey:"c-key",identity:{name:"Cal"},health:{state:"unhurt"},skills:{melee:9,resolve:9},weaponIds:["knife"]}},scene:{id:"s",immediateDanger:true},logs:[],rolls:[]})));}
const act=(s,r,a,roll=5)=>Combat.performAction(s,r,a,{rollD20:()=>roll}),pc=(id,actorId)=>({id,actorId,kind:"pc",active:true,displayName:actorId});
function structured(s,rolls=[1,5,7]){Rounds.performAction(s,gm,{type:"startStructuredPlay"});Rounds.performAction(s,gm,{type:"setParticipants",participants:[pc("pa",A),pc("pb",B),pc("pc",C)]});let i=0;Rounds.performAction(s,gm,{type:"rollInitiative"},{rollDie:()=>rolls[i++]});Rounds.performAction(s,gm,{type:"startFirstTurn"});}
function request(s,extra={},roll=5,recipient=gm){return act(s,recipient,{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"revolver",...extra},roll);}

test("ranged and melee attacks use canonical skills, consume actions, and cannot Push",()=>{const s=fixture();structured(s);let r=request(s,{bypassReaction:true},4,owner(A,"a-key"));assert.equal(r.ok,true);assert.equal(s.rolls[0].skillId,"firearms");assert.equal(s.rolls[0].rollPurpose,"rangedAttack");assert.equal(s.rolls[0].pushable,false);assert.equal(s.structuredPlay.initiativeEntries[0].actionState,"spent");const m=fixture();r=act(m,gm,{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife",bypassReaction:true},20);assert.equal(m.rolls[0].skillId,"melee");assert.equal(m.rolls[0].fumble,true);assert.equal(m.rolls[0].pushable,false);});
test("invalid target, invented weapon, stale request, and client outcomes consume nothing",()=>{const s=fixture();structured(s);for(const a of [{targetActorId:"missing",weaponId:"revolver"},{targetActorId:B,weaponId:"invented"},{targetActorId:B,weaponId:"revolver",expectedRound:99}])assert.equal(act(s,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,outcome:"success",dice:[1],...a}).ok,false);assert.equal(s.structuredPlay.initiativeEntries[0].actionState,"unspent");});
test("miss is harmless; serious and critical hits use existing health and injury shape",()=>{const miss=fixture();request(miss,{bypassReaction:true},18);assert.equal(miss.actors[B].health.state,"unhurt");assert.equal(miss.actors[B].injuries.length,0);const hit=fixture();request(hit,{bypassReaction:true},5);const id=hit.attacks[0].id;act(hit,gm,{type:"gmConfirmHitConsequence",attackId:id,description:"Gunshot wound"});assert.equal(hit.actors[B].health.state,"wounded");assert.equal(hit.actors[B].injuries.length,1);const crit=fixture();request(crit,{bypassReaction:true},1);act(crit,gm,{type:"gmConfirmHitConsequence",attackId:crit.attacks[0].id});assert.equal(crit.actors[B].health.state,"down");assert.equal(crit.actors[B].injuries[0].severity,"severe");});
test("Aim is canonical, grants one boon, expires after shot, cancels on other action, and cannot overcome impossibility",()=>{const s=fixture();act(s,owner(A,"a-key"),{type:"declareAim",actorId:A,weaponId:"revolver",targetActorId:B});request(s,{bypassReaction:true},8);assert.deepEqual(s.attacks[0].boonSources,["Aim"]);assert.equal(s.actors[A].aim.active,false);const blocked=fixture();act(blocked,gm,{type:"declareAim",actorId:A,weaponId:"revolver",targetActorId:B});act(blocked,gm,{type:"gmSetCombatContext",targetActorId:B,context:{cover:"noLineOfSight"}});assert.equal(request(blocked,{bypassReaction:true}).ok,false);assert.equal(blocked.actors[A].aim.active,true);const cancel=fixture();act(cancel,gm,{type:"declareAim",actorId:A,weaponId:"revolver"});Rounds.consumeAction(cancel,A,"Medicine check");assert.equal(cancel.actors[A].aim.active,false);});
test("cover, visibility, called shots, and firing into melee assemble required banes",()=>{for(const [context,count] of [[{cover:"partial"},1],[{cover:"strong"},2],[{visibility:"impaired"},1],[{visibility:"barelyIdentifiable"},2]]){const s=fixture();act(s,gm,{type:"gmSetCombatContext",targetActorId:B,context});request(s,{bypassReaction:true},3);assert.equal(s.attacks[0].baneSources.length,count);}for(const context of [{cover:"noLineOfSight"},{visibility:"unidentifiable"}]){const s=fixture();act(s,gm,{type:"gmSetCombatContext",targetActorId:B,context});assert.equal(request(s,{bypassReaction:true}).ok,false);}const c=fixture();act(c,gm,{type:"gmSetCombatContext",targetActorId:B,context:{cover:"strong",visibility:"barelyIdentifiable"}});request(c,{bypassReaction:true,calledShot:"precise",calledShotDescription:"hand",firingIntoMelee:true},2);assert.equal(c.attacks[0].baneSources.filter(x=>x.startsWith("called shot")).length,2);assert.equal(c.rolls[0].netModifier,-2);act(c,gm,{type:"gmConfirmHitConsequence",attackId:c.attacks[0].id});assert.match(c.actors[B].injuries[0].description,/hand/);});
test("Dodge, Parry, Take Cover, decline, duplicate, and ownership checks are atomic",()=>{for(const reaction of ["dodge","parry"]){const s=fixture();structured(s);act(s,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife"},5);const seq=s.pendingAttack.sequence;assert.equal(act(s,owner(B,"b-key"),{type:"chooseDefenseReaction",sequence:seq,reaction}).ok,true);assert.equal(s.structuredPlay.initiativeEntries[1].actionState,"reactionConsumed");assert.ok(s.attacks[0].baneSources.includes(reaction));assert.equal(act(s,owner(B,"b-key"),{type:"chooseDefenseReaction",sequence:seq,reaction}).ok,false);}const t=fixture();t.actors[B].combatContext={coverDescription:"stone wall"};structured(t);request(t,{},5,owner(A,"a-key"));const seq=t.pendingAttack.sequence;assert.equal(act(t,owner(C,"c-key"),{type:"chooseDefenseReaction",sequence:seq,reaction:"takeCover"}).ok,false);assert.equal(act(t,owner(B,"b-key"),{type:"chooseDefenseReaction",sequence:seq,reaction:"takeCover",requestedCover:"strong"}).ok,true);assert.equal(t.actors[B].combatContext.cover,"strong");});
test("unaware ranged and melee rules, awareness change, and fumble ally confirmation are host authoritative",()=>{const r=fixture();act(r,gm,{type:"gmSetCombatContext",targetActorId:B,context:{unaware:true,stationary:true}});request(r,{bypassReaction:true},3);assert.equal(r.attacks[0].boonSources.length,2);assert.equal(r.actors[B].combatContext.unaware,false);const player=fixture();assert.equal(act(player,owner(A,"a-key"),{type:"gmSetCombatContext",targetActorId:B,context:{unaware:true}}).ok,false);const melee=fixture();act(melee,gm,{type:"gmSetCombatContext",targetActorId:B,context:{unaware:true}});act(melee,gm,{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife",controlledUnawareMelee:true,bypassReaction:true});assert.equal(melee.rolls.length,0);assert.equal(melee.attacks[0].outcome,"success");const f=fixture();request(f,{bypassReaction:true,firingIntoMelee:true},20);assert.equal(f.attacks[0].allyHitConfirmed,false);act(f,gm,{type:"gmApplyFumbleConsequence",attackId:f.attacks[0].id,allyHit:true,description:"The ally is struck"});assert.equal(f.attacks[0].allyHitConfirmed,true);});
test("minor extras and nonlethal melee resolve without a separate damage track",()=>{const s=fixture();s.actors[B].healthClassification="minorExtra";request(s,{bypassReaction:true},4);act(s,gm,{type:"gmConfirmHitConsequence",attackId:s.attacks[0].id});assert.equal(s.actors[B].health.state,"down");assert.equal(s.actors[B].health.stable,true);assert.equal(s.actors[B].injuries.length,0);const n=fixture();act(n,gm,{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife",nonlethal:true,bypassReaction:true},3);act(n,gm,{type:"gmConfirmHitConsequence",attackId:n.attacks[0].id});assert.equal(n.actors[B].health.state,"wounded");n.actors[B].health.state="wounded";act(n,gm,{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife",nonlethal:true,bypassReaction:true},3);act(n,gm,{type:"gmConfirmHitConsequence",attackId:n.attacks[1].id});assert.equal(n.actors[B].incapacitated,"unconscious");});
test("projection scopes pending reactions and attack visibility and strips GM combat context",()=>{const s=fixture();structured(s);act(s,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife"},5);const pa=projectCampaignStateForRecipient(s,normalizeRecipientContext(owner(A,"a-key"))),pb=projectCampaignStateForRecipient(s,normalizeRecipientContext(owner(B,"b-key"))),pcx=projectCampaignStateForRecipient(s,normalizeRecipientContext(owner(C,"c-key")));assert.deepEqual(pa.pendingAttack.availableReactions,[]);assert.ok(pb.pendingAttack.availableReactions.length);assert.equal(pcx.pendingAttack,null);assert.equal("unaware" in pb.actors[B].combatContext,false);assert.equal("gmNotes" in pb.actors[B].combatContext,false);});
test("save/load keeps Aim and resolved hits but cancels pending attacks without duplicating consequences",()=>{const s=fixture();act(s,gm,{type:"declareAim",actorId:A,weaponId:"revolver"});const loaded=Combat.normalizeState(JSON.parse(JSON.stringify(s)),{cancelPending:true});assert.equal(loaded.actors[A].aim.active,true);const p=fixture();structured(p);act(p,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"knife"},5);assert.ok(p.pendingAttack);assert.equal(Combat.normalizeState(p,{cancelPending:true}).pendingAttack,null);const h=fixture();request(h,{bypassReaction:true},3);act(h,gm,{type:"gmConfirmHitConsequence",attackId:h.attacks[0].id});const saved=Combat.normalizeState(h,{cancelPending:true});assert.equal(saved.actors[B].health.state,"wounded");assert.equal(saved.actors[B].injuries.length,1);assert.equal(act(saved,gm,{type:"gmConfirmHitConsequence",attackId:saved.attacks[0].id}).ok,false);});
test("a triggered Ready attack uses the already-spent action exactly once",()=>{const s=fixture();structured(s);const id=s.structuredPlay.initiativeEntries[0].entryId;Rounds.performAction(s,owner(A,"a-key"),{type:"readyAction",trigger:"Ben appears",intendedAction:"shoot",expectedRound:1,expectedEntryId:id});Rounds.performAction(s,owner(A,"a-key"),{type:"triggerReadiedAction",entryId:id,expectedRound:1,expectedEntryId:s.structuredPlay.currentEntryId});assert.equal(s.structuredPlay.initiativeEntries[0].actionState,"spent");assert.equal(act(s,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"revolver",readyEntryId:id,bypassReaction:true},4).ok,true);assert.equal(s.structuredPlay.initiativeEntries[0].actionState,"spent");assert.equal(act(s,owner(A,"a-key"),{type:"requestAttack",attackerActorId:A,targetActorId:B,weaponId:"revolver",readyEntryId:id,bypassReaction:true},4).ok,false);});
